title: BCV API
description: >-
  API JSON no oficial con las tasas oficiales del Banco Central de Venezuela:
  USD, EUR, CNY, TRY, RUB.
url: https://bcv.today
baseurl: ""
repository: grupoclip/bcv-api

permalink: pretty

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

defaults:
  - scope:
      path: ""
    values:
      lang: es
  - scope:
      path: "en"
    values:
      lang: en

exclude:
  - main.py
  - requirements.txt
  - README.md
  - LICENSE
  - .gitignore
  - .gitattributes
  - .idea
  - vendor
  - Gemfile
  - Gemfile.lock
